### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by Wolfik69** [SaveMcPoland/SaveMc-Issues#38]
Propozycja wyłączenia niszczenia pól uprawnych, przez wszelakie potwory, jak i zwierzęta na działce zajętej przez Gracza.

Ps. Troszkę to irytujące, że na poziomie trudności, jakim jest Trudny, głównie potwory zatrzymały się na poziomie zygoty i są po prostu wandalami, którzy doprowadzają się takich czynów, rzecz niepojęta jak dla mnie...

~LookForMe (Nazwa użytkownika, pod którą się znajduję była niestety zajęta.)

Pozdrawiam.

**Comment by Rollczi** [comment]
zrobionie
