### ISSUE TITLE
Propozycja / Pytanie

### ISSUE THREAD

**Issue by Look-For-Me** [SaveMcPoland/SaveMc-Issues#39]
**1. )** Czy istnieje opcja wyłączenia całkowitego odradzania się złowrogich potworów na działce? (Nie pytam o to czy się da, gdyż wszystko jest możliwe, chodzi tu bardziej o to, czy wchodzi coś takiego w grę.)
**1.1 )** Nie licząc oczywiście powierzchni poza działką, byleby potwory nie mogły na nią wchodzić i/lub też się na niej odradzać.

**Ad 1. )** Natomiast jeżeli nie wchodzi to w grę, to czy byłaby możliwość wykupienia takiej opcji?

**Ps.** Propozycja, jak i samo pytanie zostało napisane, dlatego że, przy budowaniu czegokolwiek na działce, przy nadejściu pory nocnej, jest to dość mocno zauważalne, gdy nad głową lata graczowi ''30'' Fantomów, albo koło nóg biegają inne złowrogie potwory, typu szkielet, zombie itp., a przy tym zasłaniają miejsca, gdzie np. dany gracz chce postawić blok.

**Comment by Rollczi** [comment]
Zrobione
Wprowadzono komendę `/potwory` (i `/cubmob`) do ustawienia spawnowania się mobów na działce.
Potwory nadal będą mogły wejść z poza terenu działki.
