### ISSUE TITLE
Kilka propozycji.

### ISSUE THREAD

**Issue by Look-For-Me** [SaveMcPoland/SaveMc-Issues#41]
...

**Comment by Look-For-Me** [comment]
Sprawdziłem sobie to odnośnie tej Listy zadań, może jedynie Autor, jak i zapewne Właściciel obecnego Github'a.

**Comment by Rollczi** [comment]
Ogólnie to lepiej robić osobne issue na każde zadanie, tyb bardziej jeśli nie są ze sobą powiązane. 

Tak to nie mogę zamknąć jego do czasu kiedy nie skończę wszystkiego.

**Comment by Look-For-Me** [comment]
> Ogólnie to lepiej robić osobne issue na każde zadanie, tym bardziej jeśli nie są ze sobą powiązane. (jak są powiązane np /panel to można je w sumie w jedno dać)
> 
> Tak to nie mogę zamknąć jego do czasu kiedy nie skończę wszystkiego.

Hm... Zapomniałem o tym, może po prostu na razie nic nie działaj, a ja po pracy, a dokładniej po 22 jakoś, dzisiaj to zmienię i wszystko osobno zrobię.
