### ISSUE TITLE
Błąd w hook'u SuperTrailsPRO.

### ISSUE THREAD

**Issue by Look-For-Me** [SaveMcPoland/SaveMc-Issues#42]
### **[Serwer Minecraft]:**
- [ ] **1.)** Automatyczne wczytywanie cząsteczek, jak i samych skrzydełek, tak jak jest to identycznie zrobione chociażby z efektem strzały, bądź kolorem nazwy gracza, po każdym wylogowaniu, jak i ponownym zalogowaniu się danego Użytkownika.

**Comment by Rollczi** [comment]
Naprawione
