### ISSUE TITLE
Update MOTD serwera

### ISSUE THREAD

**Issue by Look-For-Me** [SaveMcPoland/SaveMc-Issues#56]
### **[Serwer Minecraft]:**
- [ ] **15.)** MOTD serwera posiada w sobie informacje o wersji, z której można się łączyć. Jest tam od 1.8.8 do 1.17.1, można by tu równie dobrze zmienić ''1.17.1'', na 1.18.1, dlatego że, można się łączyć z nowszych wersji, zaraz po 1.17.1. Sam osobiście gram na najnowszej, czyli 1.18.1 na ten moment.

**Comment by Rollczi** [comment]
![image](https://user-images.githubusercontent.com/49173834/150654248-b2fac670-d263-45af-9a25-e9278444ccbb.png)
